render_name: Wide_angle_test4_1137
output_dir: output

scene_file: assets/scene-demo-1137/0.npz
hdri_file: assets/scene-demo-1137/0.exr

render_downsample: 2

cars: 
  - new_obj_name: Police_car # should be different across each instance
    blender_file: assets/Police_car.blend
    insert_pos:
      - 18
      - 9
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Porsche-911-4s-final # should be different across each instance
    blender_file: assets/Porsche-911-4s-final.blend
    insert_pos:
      - 18
      - 6
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Tesla_cybertruck # should be different across each instance
    blender_file: assets/Tesla_cybertruck.blend
    insert_pos:
      - 18
      - 2
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Tesla_roadster # should be different across each instance
    blender_file: assets/Tesla_roadster.blend
    insert_pos:
      - 18
      - -1
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]


