render_name: Wide_angle_test3_1137
output_dir: output

scene_file: assets/scene-demo-1137/0.npz
hdri_file: assets/scene-demo-1137/0.exr

render_downsample: 2

cars: 
  - new_obj_name: Lamborghini # should be different across each instance
    blender_file: assets/Lamborghini.blend
    insert_pos:
      - 18
      - 9
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Land_Rover_range_rover # should be different across each instance
    blender_file: assets/Land_Rover_range_rover.blend
    insert_pos:
      - 18
      - 6
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: M1A2_tank # should be different across each instance
    blender_file: assets/M1A2_tank.blend
    insert_pos:
      - 18
      - 0
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

