render_name: Wide_angle_test_1137
output_dir: output

scene_file: assets/scene-demo-1137/0.npz
hdri_file: assets/scene-demo-1137/0.exr

render_downsample: 2

cars: 
  - new_obj_name: Audi_Q3_2023 # should be different across each instance
    blender_file: assets/Audi_Q3_2023.blend
    insert_pos:
      - 18
      - 9
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Benz_G # should be different across each instance
    blender_file: assets/Benz_G.blend
    insert_pos:
      - 18
      - 6
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Benz_S # should be different across each instance
    blender_file: assets/Benz_S.blend
    insert_pos:
      - 18
      - 3
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: BMW_mini # should be different across each instance
    blender_file: assets/BMW_mini.blend
    insert_pos:
      - 18
      - 0
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]