render_name: Wide_angle_test2_1137
output_dir: output

scene_file: assets/scene-demo-1137/0.npz
hdri_file: assets/scene-demo-1137/0.exr

render_downsample: 2

cars: 
  - new_obj_name: Cadillac_CT6 # should be different across each instance
    blender_file: assets/Cadillac_CT6.blend
    insert_pos:
      - 18
      - 9
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Chevrolet # should be different across each instance
    blender_file: assets/Chevrolet.blend
    insert_pos:
      - 18
      - 6
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Dodge_SRT_Hellcat # should be different across each instance
    blender_file: assets/Dodge_SRT_Hellcat.blend
    insert_pos:
      - 18
      - 3
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]

  - new_obj_name: Ferriari_f150 # should be different across each instance
    blender_file: assets/Ferriari_f150.blend
    insert_pos:
      - 18
      - 0
      - 0
    insert_rot: # rad
      - 0
      - 0
      - 3
    model_obj_name: Car # always Car
    # target_color: 
    #   material_key: car_paint # always car_paint
    #   color: [0.39, 0.39, 0.39, 1]